version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 8
    commands:
      - npm config set puppeteer_skip_chromium_download true -g
      - npm install -g resume-cli jsonresume-theme-elegant
      - npm install
      
  pre_build:
    commands:
      - mkdir public
      - resume test

  build:
    commands:
      - resume export public/index.html --theme elegant
      - resume export public/resume.pdf

  post_build:
    commands:
      - cd public/ && aws s3 sync . s3://www.jaf4.me/ --delete --size-only